//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;WINDOWS-1251&quot; ?&gt;
        ///&lt;!-- created by  Sbis 3.0 --&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:sch=&quot;http://purl.oclc.org/dsdl/schematron&quot; xmlns:usch=&quot;http://www.unisoftware.ru/schematron-extensions&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;                                    
        ///
        ///  &lt;xs:element name=&quot;Файл&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element maxOccurs=&quot;1&quot; minOccurs=&quot;1&quot; name=&quot;Документ&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///       [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string xsd__5_07__08 {
            get {
                return ResourceManager.GetString("xsd__5_07__08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;WINDOWS-1251&quot; ?&gt;
        ///&lt;!-- created by  Sbis 3.0 --&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:sch=&quot;http://purl.oclc.org/dsdl/schematron&quot; xmlns:usch=&quot;http://www.unisoftware.ru/schematron-extensions&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;                                    
        ///
        ///  &lt;xs:element name=&quot;Файл&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element maxOccurs=&quot;1&quot; minOccurs=&quot;1&quot; name=&quot;Документ&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///       [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string xsd__5_07__09 {
            get {
                return ResourceManager.GetString("xsd__5_07__09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;WINDOWS-1251&quot; ?&gt;
        ///&lt;!-- created by  Sbis 3.0 --&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:sch=&quot;http://purl.oclc.org/dsdl/schematron&quot; xmlns:usch=&quot;http://www.unisoftware.ru/schematron-extensions&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;                                    
        ///
        ///  &lt;xs:element name=&quot;Файл&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element maxOccurs=&quot;1&quot; minOccurs=&quot;1&quot; name=&quot;Документ&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///       [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string xsd__5_07__10 {
            get {
                return ResourceManager.GetString("xsd__5_07__10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;WINDOWS-1251&quot; ?&gt;
        ///&lt;!-- created by  Sbis 3.0 --&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:sch=&quot;http://purl.oclc.org/dsdl/schematron&quot; xmlns:usch=&quot;http://www.unisoftware.ru/schematron-extensions&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;                                    
        ///
        ///  &lt;xs:element name=&quot;Файл&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element maxOccurs=&quot;1&quot; minOccurs=&quot;1&quot; name=&quot;Документ&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///       [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string xsd__5_07__11 {
            get {
                return ResourceManager.GetString("xsd__5_07__11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;WINDOWS-1251&quot; ?&gt;
        ///&lt;!-- created by  Sbis 3.0 --&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:sch=&quot;http://purl.oclc.org/dsdl/schematron&quot; xmlns:usch=&quot;http://www.unisoftware.ru/schematron-extensions&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;                                    
        ///
        ///  &lt;xs:element name=&quot;Файл&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element maxOccurs=&quot;1&quot; minOccurs=&quot;1&quot; name=&quot;Документ&quot;&gt;
        ///          &lt;xs:complexType [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string xsd__5_08__08 {
            get {
                return ResourceManager.GetString("xsd__5_08__08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;WINDOWS-1251&quot; ?&gt;
        ///&lt;!-- created by  Sbis 3.0 --&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:sch=&quot;http://purl.oclc.org/dsdl/schematron&quot; xmlns:usch=&quot;http://www.unisoftware.ru/schematron-extensions&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;                                    
        ///
        ///  &lt;xs:element name=&quot;Файл&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element maxOccurs=&quot;1&quot; minOccurs=&quot;1&quot; name=&quot;Документ&quot;&gt;
        ///          &lt;xs:complexType [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string xsd__5_08__09 {
            get {
                return ResourceManager.GetString("xsd__5_08__09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;WINDOWS-1251&quot; ?&gt;
        ///&lt;!-- created by  Sbis 3.0 --&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:sch=&quot;http://purl.oclc.org/dsdl/schematron&quot; xmlns:usch=&quot;http://www.unisoftware.ru/schematron-extensions&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;                                    
        ///
        ///  &lt;xs:element name=&quot;Файл&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element maxOccurs=&quot;1&quot; minOccurs=&quot;1&quot; name=&quot;Документ&quot;&gt;
        ///          &lt;xs:complexType [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string xsd__5_08__10 {
            get {
                return ResourceManager.GetString("xsd__5_08__10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;WINDOWS-1251&quot; ?&gt;
        ///&lt;!-- created by  Sbis 3.0 --&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:sch=&quot;http://purl.oclc.org/dsdl/schematron&quot; xmlns:usch=&quot;http://www.unisoftware.ru/schematron-extensions&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;                                    
        ///
        ///  &lt;xs:element name=&quot;Файл&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element maxOccurs=&quot;1&quot; minOccurs=&quot;1&quot; name=&quot;Документ&quot;&gt;
        ///          &lt;xs:complexType [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string xsd__5_08__11 {
            get {
                return ResourceManager.GetString("xsd__5_08__11", resourceCulture);
            }
        }
    }
}
